services:
  task-service:
    container_name: task-service
    build:
      context: ./task-service
      dockerfile: Dockerfile
    env_file: ./task-service/.env
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  front:
    container_name: front
    build:
      context: ./tracker-front
      dockerfile: Dockerfile
    #    env_file: ./tracker-front/.env.docker
    ports:
      - "3000:3000"
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  gateway:
    container_name: gateway
    build:
      context: ./tracker-gateway
      dockerfile: Dockerfile
    env_file: ./tracker-gateway/.env
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  auth-service:
    container_name: auth-service
    build:
      context: ./tracket-auth-service
      dockerfile: Dockerfile
    env_file: ./tracket-auth-service/.env
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  notification-service:
    container_name: notification-service
    build:
      context: ./tracker-notification-service
      dockerfile: Dockerfile
    env_file: ./tracker-notification-service/.env
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  # Инфраструктура
  postgres:
    image: postgres:17
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tracker-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tracker-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - tracker-network

volumes:
  postgres-data:

networks:
  tracker-network:
    driver: bridge