version: '3.8'
services:
  service1:
    build:
      context: ./task-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service2:
    build:
      context: ./tracker-front
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service3:
    build:
      context: ./tracker-gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - tracker-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service4:
    build:
      context: ./tracket-auth-service
      dockerfile: Dockerfile
    networks:
      - tracker-network
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service5:
    build:
      context: ./tracker-notification-service
      dockerfile: Dockerfile
    networks:
      - tracker-network
    ports:
      - "8084:8084"

  # Инфраструктура
  postgres:
    image: postgres:17
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tracker-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tracker-network

  kafka1:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"    # Для подключения с хоста
      - "29092:29092"  # Для подключения из Docker-сети
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - tracker-network

volumes:
  postgres-data:

networks:
  tracker-network:
    driver: bridge