name: CI/CD Pipeline

on:
  push:
    branches: [master, develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [task-service, tracker-front, tracker-gateway, tracket-auth-service, tracker-notification-service]
        include:
          - service: task-service
            image_name: task-service
          - service: tracker-front
            image_name: front
          - service: tracker-gateway
            image_name: gateway
          - service: tracket-auth-service
            image_name: auth-service
          - service: tracker-notification-service
            image_name: notification-service

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Force update submodules to latest commits
        run: |
          git submodule deinit --all -f
          git submodule update --init --remote --recursive --force
          git submodule foreach 'git fetch --all --force && git reset --hard origin/main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:buildcache,mode=max